app_gastos_blog_categorias:
    path:     /blog/categorias
    defaults: { _controller: AppGastosBlogBundle:Categoria:index }

app_gastos_blog_insertar_categoria:
    path:     /blog/insertar-categoria
    defaults: { _controller: AppGastosBlogBundle:Categoria:insertar }

app_gastos_blog_editar_categoria:
    path:     /blog/editar/{id}
    defaults: { _controller: AppGastosBlogBundle:Categoria:editar }

app_gastos_blog_ver_categoria:
    path:     /blog/ver-{titulo}
    defaults: { _controller: AppGastosBlogBundle:veCategoriar:ver }
    
app_gastos_blog_eliminar_categoria:
    path:     /blog/categoria/eliminar/{id}
    defaults: { _controller: AppGastosBlogBundle:Categoria:eliminar }

app_gastos_blog_articulos:
    path:     /blog/articulos
    defaults: { _controller: AppGastosBlogBundle:Articulos:index }
