services:
#    app_gastos_blog.example:
#        class: AppGastos\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    app_gastos_blog.form.type.categoria:
#        class: AppGastos\BlogBundle\Form\Type\CategoriaType
#        tags:
#            - { name: form.type, alias: categoria }
