<?php

namespace AppGastos\BlogBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppGastosBlogBundle:Categoria c ORDER BY c.titulo ASC'
            )
            ->getResult();
    }
}
